version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: labshop-api:latest
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      ENV: e2e
      SECRET_KEY: ${SECRET_KEY}
      MONGODB_URL: mongodb://db:27017
      MONGODB_DB: labshop
  
  # db:
  #   image: mongo:8.2.4-noble
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongo-data:/data/db
  
  db-replica:
    image: mongo:8.2.4-noble
    container_name: labshop-mongo-replica
    ports:
      - "27017:27017"
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    healthcheck:
      test: mongosh --port 27017 --eval "rs.status().ok || rs.initiate({_id:'rs0',members:[{_id:0,host:'db:27017'}]})"
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mongo-data:/data/db
    command: mongod --replSet rs0 --bind_ip_all
  db-replica-init:
    image: mongo:8.2.4-noble
    container_name: labshop-mongo-replica-init
    depends_on:
      - db-replica
    restart: "no" # We only want this to run once and then stop
    command: >
      bash -c "
        echo 'Waiting for MongoDB to start...'
        sleep 5
        echo 'Initializing replica set...'
        mongosh --host mongodb:27017 --eval 'rs.initiate({_id: \"rs0\", members: [{_id: 0, host: \"127.0.0.1:27017\"}]})'
        echo 'Replica set initialized.'
      "
    
volumes:
  mongo-data:
