name: API Test

on:
  push:
    branches: [main]
    paths:
      - "api/**"
      - ".github/workflows/api-api-test.yaml"
  pull_request:
    branches: [main]
    paths:
      - "api/**"
      - ".github/workflows/api-api-test.yaml"

defaults:
  run:
    working-directory: api

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3
      - name: Build docker image
        run: docker build -t built-image .
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.14"

      - name: Initialise container
        run: |
          docker compose -f docker-compose.test.yaml up -d
          sleep 10 # Wait for the container to be ready
      
      - name: Initalise Python
        uses: actions/setup-python@v6 
        with:
          python-version: "3.14.2"

      - name: Run tests
        run: |
          pip install -r requirements.txt
          echo "Running tests"
          pytest e2e/ -v --tb=short
